apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-visoft-dev
spec:
  secretName: example-visoft-dev-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - visoft.dev
  privateKey:
    algorithm: ECDSA
  dnsNames:
    - example.visoft.dev
  issuerRef:
    name: visoft-dev-dns01
    kind: ClusterIssuer
